name: Hello World
author: Me
description: A description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Me
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node16"
  main: "dist/index.js"
